apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-inventory-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerce-inventory
  template:
    metadata:
      labels:
        app: ecommerce-inventory
    spec:
      containers:
      - name: inventory-container
        image: ecommerce-inventory-app:latest  # Make sure this image exists locally or is in your registry
        ports:
        - containerPort: 5000
