apiVersion: v1
kind: Service
metadata:
  name: ecommerce-inventory-service
spec:
  selector:
    app: ecommerce-inventory
  ports:
    - protocol: TCP
      port: 80         # External port to access the service
      targetPort: 5000 # Port the container is using
  type: NodePort      # Use NodePort to expose the service on a port of your Kubernetes node
