apiVersion: v1
kind: Service
metadata:
  name: ecommerce-inventory-service
spec:
  selector:
    app: ecommerce-inventory
  ports:
    - protocol: TCP
      port: 80         # Exposed port
      targetPort: 5000 # Container port
  type: NodePort      # This type makes your service accessible externally, via a port on the Node
